name: meteor_music
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  spotify: ^0.8.0
  url_launcher: ^6.1.9
  webview_flutter: ^4.0.2
  uni_links: ^0.5.1
  go_router: ^6.0.6
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.6.1
  spotify_sdk: ^2.3.0
  sliver_tools: ^0.2.8
  dio: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
